version: "3.1"

services:
  db:
    image: sameersbn/postgresql:10-2
    restart: always
    environment:
      PG_PASSWORD: password
      DB_NAME: slsdjango
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "35434:5432"
  redis:
    image: redis:5.0-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    ports:
      - "36380:6379"
volumes:
  pgdata:
  redisdata:
